variable "credentials_file_path" {}
variable "project" {}
variable "region" {}
variable "zone" {}
variable "machine" {}
variable "image" {}
variable "ubuntu_image" {}
variable "license_file" {}
# vpc module
variable "vpcs" {}
# subnet module
variable "subnets" {}
variable "subnet_cidrs" {}
